export default [
    {
        title:'首页',
        key:'/admin/home'
    },
    {
        title:'用户',
        key:'/admin/user',
        children:[
            {
                title:'用户列表',
                key:'/admin/user/userlist'
            },
        ]
    },
    {
        title:'订单',
        key:'/admin/order',
        children:[
            {
                title:'订单列表',
                key:'/admin/order/orderList'
            },
        ]
    },
    {
        title:'UI',
        key:'/admin/ui',
        children:[
            {
                title:'按钮组件',
                key:'/admin/ui/button'
            },
            {
                title:'弹框组件',
                key:'/admin/ui/modals'
            },
            {
                title:'表格组件',
                key:'/admin/ui/table'
            },
            {
                title:'动态表格',
                key:'/admin/ui/DynamicTables'
            },
        ]
    },
]